load(
    "@rules_rs//rs:rust_binary.bzl",
    "rust_binary",
)
load(
    "@rules_rs//rs:rust_test.bzl",
    "rust_test",
)
load("@rules_rust_prost//:defs.bzl", "rust_prost_library")

rust_binary(
    name = "bin",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "@crates//:anyhow",
        "@crates//:clap",
        "@crates//:futures",
        "@crates//:rand",
        "@crates//:tokio",
        "@crates//:tokio-stream",
        "@crates//:tonic",
        "@crates//:url",
        "//third_party/googleapis/google/devtools/build/v1:build_rust_proto",
    ],
    binary_name = "nbes",
)

rust_test(
    name = "test",
    size = "small",
    crate = ":bin",
)
