[package]
name = "nbes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.11"
futures = "0.3.32"
hyper-util = "0.1.20"
log = "0.4.33"
prost = "0.14.4"
prost-types = "0.14.4"
protoc-gen-prost = "0.5.0"
protoc-gen-tonic = "0.5.0"
rand = "0.10.1"
serde = {version = "1.0.229", features = ["derive"]}
serde_yaml_ng = "0.10.0"
tokio = {version = "1.52.2", features = ["macros", "rt-multi-thread", "signal"]}
tokio-stream = {version = "0.1.18", features = ["sync"]}
tonic = { version = "0.14.6", features = ["tls-aws-lc", "tls-native-roots"] }
tonic-prost = "0.14.6"
tower = "0.5.3"
url = {version = "2.5.8", features = ["serde", "serde_derive"]}

[dev-dependencies]
rcgen = "0.14.8"
tempfile = "3.27.0"
uuid = {version = "1.23.4", features = ["v4"]}
