name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: bazel-contrib/setup-bazel@083175551ceeceebc757ebee2127fde78840ca77 # 0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelrc: common --config=ci --config=release
      - name: docker login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build deliverables
        run: |
          bazel build //:multiplatform_bins //:image.push
      - name: push images
        run: |
          bazel run //:image.push
      - name: collect-artifacts
        run: |
          mv bazel-out/aarch64-apple-darwin-opt/bin/nbes nbes_darwin_arm64
          mv bazel-out/aarch64-unknown-linux-musl-opt/bin/nbes nbes_linux_arm64
          mv bazel-out/x86_64-apple-darwin-opt/bin/nbes nbes_darwin_amd64
          mv bazel-out/x86_64-unknown-linux-musl-opt/bin/nbes nbes_linux_amd64
      - name: release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: nbes-*
