name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: bazel-contrib/setup-bazel@083175551ceeceebc757ebee2127fde78840ca77 # 0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelrc: common --config=ci --config=release
      - name: push images
        run: |
          bazel run //:image.push
      - name: build deliverables
        run: |
          bazel build //:multiplatform_bins //:image.push
      - name: collect-artifacts
        run: |
          mv bazel-out/linux_x86_64_gnu.2.28-opt/bin/nbes nbes-linux-amd64
          mv bazel-out/linux_arm64_gnu.2.28-opt/bin/nbes nbes-linux-arm64
          mv bazel-out/macos_amd64-opt/bin/nbes nbes-darwin-amd64
          mv bazel-out/macos_arm64-opt/bin/nbes nbes-darwin-arm64
      - name: release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: nbes-*
